server:
  port: 8081
#  context-path: /girl
cupsize: A
girl:
  name: "haha"
  password: "1234"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



